// <auto-generated />
using System;
using AseAudit.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AseAudit.Infrastructure.Migrations
{
    [DbContext(typeof(AuditDbContext))]
    [Migration("20260505153338_ExpandFireWallRuleNameLengths")]
    partial class ExpandFireWallRuleNameLengths
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AseAudit.Core.Entities.FireWallRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Action");

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedTime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("DestinationIP")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("DestinationIP");

                    b.Property<string>("Direction")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Direction");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(512)
                        .HasColumnType("nvarchar(512)")
                        .HasColumnName("DisplayName");

                    b.Property<string>("HostName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("HostName");

                    b.Property<string>("MACAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("MACAddress");

                    b.Property<string>("Port")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("LocalPort");

                    b.Property<string>("Profile")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Profile");

                    b.Property<string>("Protocol")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Protocol");

                    b.Property<string>("RemotePort")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("RemotePort");

                    b.Property<string>("RuleName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)")
                        .HasColumnName("RuleName");

                    b.Property<string>("SourceIP")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("SourceIP");

                    b.Property<string>("Status")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.HasIndex("HostName")
                        .HasDatabaseName("IX_FireWallRule_HostName");

                    b.ToTable("FireWallRule");
                });

            modelBuilder.Entity("AseAudit.Core.Entities.IdentificationAmAccount", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("AccountName");

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedTime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("HostName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("HostName");

                    b.Property<string>("MACAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("MACAddress");

                    b.Property<bool?>("PasswordRequired")
                        .HasColumnType("bit")
                        .HasColumnName("PasswordRequired");

                    b.Property<string>("Status")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Status");

                    b.HasKey("Id");

                    b.HasIndex("HostName")
                        .HasDatabaseName("IX_Identification_AM_Account_HostName");

                    b.ToTable("Identification_AM_Account");
                });

            modelBuilder.Entity("AseAudit.Core.Entities.IdentificationAmRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedTime")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedTime")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<int>("DomainRole")
                        .HasColumnType("int")
                        .HasColumnName("DomainRole");

                    b.Property<bool>("EveryoneIncludesAnonymous")
                        .HasColumnType("bit")
                        .HasColumnName("EveryoneIncludesAnonymous");

                    b.Property<string>("HostName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("HostName");

                    b.Property<string>("MACAddress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)")
                        .HasColumnName("MACAddress");

                    b.Property<bool>("RestrictAnonymous")
                        .HasColumnType("bit")
                        .HasColumnName("RestrictAnonymous");

                    b.Property<bool>("RestrictAnonymousSAM")
                        .HasColumnType("bit")
                        .HasColumnName("RestrictAnonymousSAM");

                    b.Property<string>("UserDomain")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("UserDomain");

                    b.HasKey("Id");

                    b.HasIndex("HostName")
                        .HasDatabaseName("IX_Identification_AM_rule_HostName");

                    b.ToTable("Identification_AM_rule");
                });
#pragma warning restore 612, 618
        }
    }
}
